server {
    listen 80;
    
    location ^~ /api/docs/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/redoc.html;
    }

    location ~ ^/(api|admin)/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /backend_static/ {
        alias /app/static/;
        try_files $uri $uri/ =404;
    }


    location /media/ {
        alias /app/media/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}