# Generated by Django 5.2.1 on 2025-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
