# Generated by Django 5.2.1 on 2025-05-28 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не менее 1 минуты.'), django.core.validators.MaxValueValidator(1441, message='Время приготовления не более 24 часов.')], verbose_name='Время готовки (минуты)'),
        ),
    ]
